name: PPAP

on:
  push:
    branches:
      - main

jobs:
  ppap-sync:
    name: PPAP sync
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4